### PR TITLE
Option to group single recordings in folders / Initial series recording features

### PR DESCRIPTION
**Pull request by patrickplummers4**
Adds a setting to group single recordings into folders so the recording
list only contains show names (default is false to preserve the same
functionality as before).  Since the settings.xml changed, strings.po
will need to be updated for all languages.  (English is provided so
far).

### CODE REVIEW

**Comment by hudokkow** [comment]
@margro, can you review?

**Comment by patrickplummers4** [comment]
Let me know if you need more details.  Basically the new flow is when a Timer is requested by the user, the addon will now check if the show is part of a series (check for a series number from the epg) and if so pop up the new dialog for recording preferences.  Based on those options, a new schedule is created calling the existing backend functions in ArgusTV.  If the user wants to delete a Timer, if the Timer was a series schedule, then a new dialog will popup asking if they want to delete the whole schedule or just the current show.

**Comment by margro** [comment]
I can't test it right now since I don't have a working Argus TV backend available. Code extensions look fine to me. Nice work!

@Red-F: If you have time and a working backend, Patrick has added some nice new features for you to test ;-)

Only request code-wise is to match the coding style.
Furthermore, before we can merge this, create a separate branch with only the first two commits or remove them from your master branch. The binary builds and the merge commit should be removed before merging.

**Comment by patrickplummers4** [comment]
Excellent, I will do that.  Thank you Marcel!

**Comment by Red-F** [comment]
@margro Just got my local development environment adjusted to the new cmake build environment :-)

@patrickplummers4 Patrick you beat me to the option to group single recordings into a folder, it was a feature request asked by my wife as well :-) Would you mind splitting this PR into two feature branches? One related to the 'group single recordings into a folder' and the second one containing the changes for the series recording? And please rebase and squash it so that the master branch will stay a little cleaner. Thx, Fred

**Comment by patrickplummers4** [comment]
Sure I will do that. I'm new to git and it merged two commits together automatically which I didn't want. :)

Sent from my Android phone

-----Original Message-----

**Pull request closed without merging**
