### PR TITLE
Option for single recordings to be in a folder

### PR DESCRIPTION
**Pull request by patrickplummers4**
New pull request for just this feature: Make it an option to not allow single recordings in the recordings view. All recordings will be grouped into a series folder. The default is false however to preserve existing functionality.

### CODE REVIEW

**Comment by hudokkow** [comment]
Please fix indent, drop https://github.com/patrickplummers4/pvr.argustv/commit/54fda08e92d0c9162f4c46e295d65959f869af6e and squash.

If you need help with git-fu just let me know.

Thanks.

**Comment by patrickplummers4** [comment]
Which file has the indent problem?  I’m not seeing it…

**Comment by patrickplummers4** [comment]
I saw what you meant – should be fixed now.   Squashed also.

**Comment by Jalle19** [comment]
There are still some whitespace issues, did you forget to force push your changes?

**Comment by patrickplummers4** [comment]
It was resubmitted as #10

**Pull request closed without merging**
