### PR TITLE
Sync with API 1.9.5

### PR DESCRIPTION
**Pull request by bkuhls**
[  5%] Building CXX object src/lib/tsreader/CMakeFiles/tsreader.dir/FileReader.cpp.o
In file included from /home/fli4l/br3/output/build/kodi-pvr-argustv-b6a58d36b80dc9c13800c3a28824df9817d02e9b/src/lib/tsreader/FileReader.cpp:36:0:
/home/fli4l/br3/output/build/kodi-pvr-argustv-b6a58d36b80dc9c13800c3a28824df9817d02e9b/src/client.h:29:30: fatal error: kodi/libXBMC_gui.h: No such file or directory
 #include "kodi/libXBMC_gui.h"
                              ^
compilation terminated.

### CODE REVIEW

**Comment by hudokkow** [comment]
You need to bump addon version https://github.com/kodi-pvr/pvr.argustv/blob/master/pvr.argustv/addon.xml#L4
and API https://github.com/kodi-pvr/pvr.argustv/blob/master/pvr.argustv/addon.xml#L9
to 1.9.5

See https://github.com/kodi-pvr/pvr.vuplus/commit/05e784ec1000375980c5814cbdc54092476ec0e5 for reference.

**Comment by bkuhls** [comment]
@hudokkow done

**Comment by bkuhls** [comment]
patch updated again

**Comment by hudokkow** [comment]
Thanks.
@AlwinEsch, can you pull the trigger on this PR, https://github.com/kodi-pvr/pvr.mythtv/pull/1, https://github.com/kodi-pvr/pvr.filmon/pull/4, https://github.com/kodi-pvr/pvr.hts/pulls and https://github.com/kodi-pvr/pvr.nextpvr/pull/1

It would be nice to start testing with nightlies. Right now most addons are broken for non devs.

I'll put everything together in https://github.com/hudokkow/kodi/commits/pvr_update and PR to Kodi's side.

**Pull request merged**
