### PR TITLE
try to make debian build test via github workflow

### PR DESCRIPTION
**Pull request by AlwinEsch**
Request to test about.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Hi @wsnipex, @ksooo, @lrusak, @phunkyfish, @yol, seems good to work with a Debian build test on it.

On every build the Ubuntu seems from scratch and can confirm needed depends becomes installed new.
See also here https://github.com/kodi-pvr/pvr.argustv/runs/3603885256?check_suite_focus=true#step:4:34, where temporary the "ppa:team-xbmc/xbmc-nightly;" set was prevented.

How good can be this way used on mostly all binary addons and to have back the Debian build test?

The other builds where I comment out on the build.yml are not direct matter, for this are also the other CI's good (specially Azure where do this way on Windows).

**Review by wsnipex — APPROVED** [review]
Looks good to me!
Should work for all addons(besides many game addons that fail to build on the ppa due to missing dependencies)

**Review by yol — COMMENTED** [review]
I can't really comment on the content, but +1 for using GitHub actions

**Comment by AlwinEsch** [comment]
Thanks a lot! @yol cool and yes, I'm was a bit unsure about the github actions, not that there are also limitations, let try :smiley:.
Will bring in here and to add on all others.

**Pull request merged**
