### PR TITLE
Fix OSX xcode6.1 brew update and jsoncpp issues

### PR DESCRIPTION
**Pull request by zcsizmadia**

### CODE REVIEW

**Comment by hudokkow** [comment]
Thanks!

**Comment by ksooo** [comment]
@zcsizmadia @hudokkow seems to cause linker error:

[100%] Linking CXX shared library pvr.argustv.dylib

Undefined symbols for architecture x86_64:

  "Json::Value::operator=(Json::Value)", referenced from:

      cActiveRecording::Parse(Json::Value const&) in activerecording.cpp.o

      ArgusTV::TuneLiveStream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ArgusTV::ChannelType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in argustvrpc.cpp.o

      ArgusTV::GetFullRecordingsForTitle(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Json::Value&) in argustvrpc.cpp.o

      ArgusTV::AddOneTimeSchedule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, Json::Value&) in argustvrpc.cpp.o

      ArgusTV::AddManualSchedule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long, long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, Json::Value&) in argustvrpc.cpp.o

      cUpcomingRecording::Parse(Json::Value const&) in upcomingrecording.cpp.o

  "Json::Value::operator[](int)", referenced from:

      CEventsThread::HandleEvents(Json::Value) in EventsThread.cpp.o

      cPVRClientArgusTV::ShareErrorsFound() in pvrclient-argustv.cpp.o

      cPVRClientArgusTV::GetEpg(ADDON_HANDLE_STRUCT*, PVR_CHANNEL const&, long, long) in pvrclient-argustv.cpp.o

      cPVRClientArgusTV::GetChannels(ADDON_HANDLE_STRUCT*, bool) in pvrclient-argustv.cpp.o

      cPVRClientArgusTV::GetChannelGroups(ADDON_HANDLE_STRUCT*, bool) in pvrclient-argustv.cpp.o

      cPVRClientArgusTV::GetChannelGroupMembers(ADDON_HANDLE_STRUCT*, PVR_CHANNEL_GROUP const&) in pvrclient-argustv.cpp.o

      cPVRClientArgusTV::GetNumRecordings() in pvrclient-argustv.cpp.o

      ...

  "Json::Value::operator[](int) const", referenced from:

      Json::printValueTree(Json::Value const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in utils.cpp.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[5]: *** [pvr.argustv.2.2.1.dylib] Error 1

Will revert the commit.

**Comment by ksooo** [comment]
UPDATE: Did not revert as this does not fix the problem.

@zcsizmadia could you please take a look? Other addons are also suffering from the linker problem.

**Comment by hudokkow** [comment]
Uh? This was building fine until https://github.com/kodi-pvr/pvr.argustv/commit/45a64b7ddb6926adfba18df3ec3a1c931a7d16bc got merged. See [build history] (https://travis-ci.org/kodi-pvr/pvr.argustv/builds).
Sorry for not being more helpful but I haven't been paying attention to PVR for some time now.

**Comment by ksooo** [comment]
Whatever the reason is, currently this and other pvr add-ons using cppjson cannot be built on macos using the current travis script. Generally they build, but not with travis.

**Comment by zcsizmadia** [comment]
I think problem is that in brew json got updated to 1.6.5. I've noticed that the travis scripts are changed now to use absolute path in the cmake call. I do not know if it by design or a side effect, but to compile the addon dependencies statically into the addon lib, you have to use absolute paths, otherwise the addon dependencies are ignored. (i did this all the time with windows, see my build example in the Readme in pvr.hdhomerun).
One solution is that we remove the brew install from the travis script, or we install an older version (0.6.x) of json with brew.
How does the Jenkins build the addon (Statically or dynamically linking against the deps)?
If we do not mind statically bilding the deps into the addon on travis, we can remove the whole apt-get/brew magic.

I did a test build on pvr.hdhomerun where I removed the whole before_install script from travis.yml, and everything builds.

**Comment by zcsizmadia** [comment]
Created a PR to pvr.hdhomerun ro remove the whole before_install script and seems to solve the travis build issue.

**Pull request merged**
