### PR TITLE
Coverity fixes

### PR DESCRIPTION
**Pull request by margro**
This should fix all pending coverity scan issues

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@ksooo @xhaggi @margro or who ever.
We're almost nearing RC1 and then heading to final release. Are these fixes somethnig that could be included?

**Comment by ksooo** [comment]
Despite from this, the changes looking good to me. 

@margro Please update the "strncpy" commit and add a separate commit to this PR for changelog update and addon version bump.

@MartijnKaijser if @margro does the changes I mentioned above it should be fine to include this for RC1.

**Comment by margro** [comment]
@ksooo: sorry but I won't remove the macro. I'm using identical code in my pvr.mediaportal.tvserver addon and I want to keep it similar where possible. The macro has already proven its usage in my other addon. The changes are safe for RC1

**Comment by ksooo** [comment]
@margro Okay, at the end it's just personal style and if you are happy with that...

**Comment by MartijnKaijser** [comment]
@margro string translation just got updated so it needs a rebase now.

**Comment by margro** [comment]
@MartijnKaijser Rebase + version update done. Will also send a separate PR for Isengard

**Pull request merged**
