### PR TITLE
Resubmit changes for new group all recordings into folders

### PR DESCRIPTION
**Pull request by patrickplummers4**
New pull request for just this feature:  Make it an option to not allow single recordings in the reocrdings view.  All recordings will be grouped into a series folder.  The default is false however to preserve existing functionality.

### CODE REVIEW

**Comment by patrickplummers4** [comment]
Anybody ready to review this?  This is just the single recordings in folder option.

**Comment by patrickplummers4** [comment]
Anyone?  This commit is getting behind again.

**Comment by piejanssens** [comment]
ping ping @margro @hudokkow

@patrickplummers4 What's the status on the series recording?

**Comment by patrickplummers4** [comment]
It’s done and tested but I’m waiting on a repo owner to merge the previous pull requests.

**Comment by piejanssens** [comment]
You can already submit a PR for the recordings commit and comment that it depends on this PR.
Before this PR can be merged, the merge conflicts will need to be resolved...

**Comment by patrickplummers4** [comment]
I haven’t wanted to do that since in the past multiple commits that come after the pull request I’ve done have been accepted causing merge conflicts.   Mostly due to the changelog file comments.   It’s causing a lot of unnecessary work.

**Comment by piejanssens** [comment]
I understand, but it has to be done anyway.

**Comment by patrickplummers4** [comment]
OK, I closed #8 and resubmitted as #9 with the conflict resolved.

I’ll submit the series recording if #9 is accepted.

**Comment by piejanssens** [comment]
I think the series recording you created will become obsolete once https://github.com/xbmc/xbmc/pull/7079 is merged in (Kodi 16). Not sure about this PR.
What's your take on it guys?

**Comment by patrickplummers4** [comment]
I agree, it looks nice.   It was rumored when I worked on the series record for ArgusTV a couple of months back but there was no ETA so I went ahead and did it.  If they can merge the PR soon I will be very happy.   I offer to work on the changes for ArgusTV since I’m now pretty familiar with the JSON calls to pass all the series info to the PVR.   I purposefully made mine fairly simplistic – mine only supports basic “Any Day” recording for a given series but with options to select first run (premiere) vs repeats or both.  Based on the screenshots provided in the PR comments it should be reasonably easy to adapt.   Right now I’m actually passing most of this data but hardcoded with defaults since there was no UI to represent the many many options in ArgusTV.

ArgusTV is well known for being extremely adaptable in its recording filters, so even this might not cover everything – but (as always) if something isn’t represented in the UI, they can still do it on the back end app or the web app.

**Comment by hudokkow** [comment]
@patrickplummers4, https://github.com/xbmc/xbmc/pull/7079 should go in as soon as Isengard is branched and master is open for business again.

Feel free to continue contributing code for this or any other add-on. I promise next time we'll review it much faster.

**Comment by ksooo** [comment]
@patrickplummers4 Cool to have you on board. Feel free to bother me with all kind of questions / feedback regarding the new series recording stuff.

**Comment by patrickplummers4** [comment]
Thank you, much appreciated.

**Pull request closed without merging**
